Add notifications like FireProtection module
maros/Zway-EventWatcher pull request #1
Opened 2016-10-15 13:47 UTC by bjoern812

Dear Maros,
I like the way that zway uses a notification style (email,pushover) in the module "FireProtection".
Using your great modules, especially the SecurityZone, I search for a way to use this "notification style",
so I take your EventWatcher and coded (more a copy&paste) the notification used in the "FireProtection"
module.
Maybe, you can have a look at it and if you like it, adopt it to your repo.

Thanks,
Björn

2016-10-17 06:29 UTC, maros requested changes
Thank you for your PR. I'd like to ask  you to make some minor amendments before I can finally accept and merge this PR

Thank you!

2016-10-17 06:29 UTC, maros commented on index.js
> +    this.CallbackEvent  = undefined;
Shouldn't this be called 'callbackEvent' (lowecase 'c')

2016-10-17 06:29 UTC, maros commented on index.js
> +Version: 1.05
Please don't increment the version. I have scripts for building releases that will get confused by manual changes

2016-10-17 06:29 UTC, maros commented on module.json
> +   "version" : "1.05"
No manual version bumps please

2016-10-17 06:29 UTC, maros commented on module.json
> +                                    "type": "textarea"
Maybe add a "helper" field that indicates that the message will only be used if the event does not have its own message

2016-10-17 19:55 UTC, bjoern812 commented on index.js
> +    this.CallbackEvent  = undefined;
Yes, of cource. You are right!

2016-10-17 19:56 UTC, bjoern812 commented on module.json
> +                                    "type": "textarea"
Add a hellper field

2016-10-17 19:56 UTC, bjoern812 commented on module.json
> +   "version" : "1.05"
Reverse the change of the versions

2016-10-17 20:00 UTC, bjoern812 commented
Hi Maros,

thank you for your reply. I totally new to Github, so I changed my master branch and now I don't know
if I have todo? I see my changed files in this pull request. Must I create a new pull request or anything else?
Hope you may help me?

2016-10-18 05:22 UTC, merged

2016-10-18 05:23 UTC, maros commented
Thank you for the PR. The PR was fine. For the future however, I'd recommend to make fewer commits (ie. not one commit per changed file)